version: '3'
services:
    hidiki-jenkins:
        container_name: hidiki-jenkins
        image: 'jendiki'
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./jenkins_home:/var/jenkins_home
